version: '3'
services:
  #授权服务
  authorization-server:
    image: av/authorization-server:latest
    container_name: av-authorization-server
    restart: always
    networks:
      - av-net
    ports:
      - 8000:8000
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - authentication-server

  #认证服务
  authentication-server:
    image: av/authentication-server:latest
    container_name: av-authentication-server
    restart: always
    networks:
      - av-net
    ports:
      - 8001:8001
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - organization

  #组织服务
  organization:
    image: av/organization:latest
    container_name: av-organization
    restart: always
    networks:
      - av-net
    ports:
      - 8010:8010
    env_file: .env
    environment:
      TZ: Asia/Shanghai